### ISSUE TITLE
Tangent???

### ISSUE THREAD

**Issue by asdasdqwdqwfsdf** [jfriedlein/usrmat_LS-Dyna_Fortran#1]
Hello!

If we develop UMAT in Ls-Dyna, must we  write code for Tangent? 
As far as I know Ls-Dyna uses explicit FE solvers...

Best

**Comment by jfriedlein** [comment]
Hi @asdasdqwdqwfsdf, 

thank you for that good point. LS-Dyna uses a "one-code setup" containing explicit and implicit solvers.
![LS-Dyna - overview one-code solvers](https://user-images.githubusercontent.com/58786257/84353090-c8d8aa80-abbe-11ea-8d84-71089d0b9704.png)
Often it is very straightforward to switch from implicit to explicit (just the option "IMFLAG"). So, you can also solve problems implicitly in LS-Dyna requiring the tangent utan ([Tips and tricks for implicit](https://www.dynamore.de/de/download/presentation/dokumente/download-informationstag-Implizit-2016/05-2016-02-dynamore-infotag-implizit-tipstricks.pdf)).
However as noted in section "Our first user material" step 7, you can often test the material model in "umat" by solving it explicitly without the need for the "utan" function. To sum up, you don't need the tangent to solve problems explicitly, but for implicit simulations it is crucial (LS-Dyna user manual Vol. I, Appendix A).
I will continue the documentation this weekend, so stay tuned.

Best regards,
Johannes

**Comment by asdasdqwdqwfsdf** [comment]
@jfriedlein Hello Johnannes,

thanks for your reply! Possibly, one more thing, **at large deformations**, tangente for abaqus and ls Dyna should **NOT** be used by the same formulations? OR?

Best!

**Comment by jfriedlein** [comment]
@asdasdqwdqwfsdf 
Can you specify your question:  What do you mean by "same formulation" and why do you propose not using it?
